'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let items=[],original=[],category='Alle items',onlyFav=false,favs=new Set();
function read(key){try{return JSON.parse(localStorage.getItem(key))}catch{return null}}
function save(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}}
const savedFavs=read('oh-favorites');if(Array.isArray(savedFavs))favs=new Set(savedFavs.filter(x=>typeof x==='string'));
function safeUrl(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}}
function validate(data){if(!Array.isArray(data)||data.length>20000)throw Error('Gebruik een JSON-lijst met maximaal 20.000 items.');const seen=new Set();for(const i of data){if(!i||typeof i!=='object'||['id','name','nl','category','description','obtain','source'].some(k=>typeof i[k]!=='string')||!i.id||seen.has(i.id)||!safeUrl(i.source))throw Error('Elk item heeft een unieke id, name, nl, category, description, obtain en geldige bron-URL nodig.');seen.add(i.id);if(i.recipe!==undefined&&(!Array.isArray(i.recipe)||i.recipe.some(r=>!r||typeof r.id!=='string'||!Number.isFinite(r.amount)||r.amount<=0)))throw Error('Een recept heeft ingrediënten met id en een positief amount nodig.');}return data;}
function art(i){let color=i.id.includes('copper')?'#c39162':i.category==='Consumables'||i.id.includes('water')?'#7aacbb':i.id==='charcoal'?'#637369':'#b6c681';let shape=i.category==='Bouwobjecten'?'<path d="M25 30h50v52H25z" fill="'+color+'"/><path d="M20 30l30-18 30 18H20" fill="#dce7b5"/><path d="M38 50h24v32H38z" fill="#22352b"/><path d="M41 72l9-16 10 16" fill="#cb965b"/>':i.id.includes('water')?'<path d="M40 13h20v12l12 15v42H28V40l12-15z" fill="'+color+'"/><path d="M32 53h36v25H32z" fill="#4c8699"/><path d="M40 13h20v9H40z" fill="#cdd6c7"/>':'<path d="M17 37l30-24 33 13 9 41-38 21-35-21z" fill="'+color+'"/><path d="M17 37l34 14-4-38 33 13-29 25 38 16-38 21V51L16 67z" fill="#ffffff22"/><path d="M51 51l29-25 9 41-38 21z" fill="#0002"/>';return '<div class="art" aria-hidden="true"><svg viewBox="0 0 100 100">'+shape+'</svg></div>';}
function render(){const cats=['Alle items',...new Set(items.map(i=>i.category))];if(!cats.includes(category))category='Alle items';$('filters').innerHTML=cats.map(c=>`<button data-cat="${esc(c)}" class="${c===category?'active':''}" aria-pressed="${c===category}">${esc(c)}</button>`).join('');const q=$('search').value.toLocaleLowerCase('nl').trim();const list=items.filter(i=>(category==='Alle items'||i.category===category)&&(!onlyFav||favs.has(i.id))&&[i.name,i.nl,i.description,i.category,i.obtain].join(' ').toLocaleLowerCase('nl').includes(q)).sort((a,b)=>a.name.localeCompare(b.name)*($('sort').value==='za'?-1:1));$('resultCount').textContent=list.length+' van '+items.length+' items';$('favCount').textContent=favs.size;$('listTitle').textContent=onlyFav?'Jouw favorieten':'Itemcatalogus';$('all').classList.toggle('active',!onlyFav);$('favorites').classList.toggle('active',onlyFav);$('grid').innerHTML=list.map(i=>`<article class="card"><button class="star ${favs.has(i.id)?'saved':''}" data-star="${esc(i.id)}" aria-label="${favs.has(i.id)?'Verwijder uit':'Voeg toe aan'} favorieten: ${esc(i.name)}" aria-pressed="${favs.has(i.id)}">${favs.has(i.id)?'★':'☆'}</button><button class="card-main" data-item="${esc(i.id)}">${art(i)}<div class="card-body"><span class="category">${esc(i.category)}</span><h3>${esc(i.name)}</h3><span class="nl">${esc(i.nl)}</span><p>${esc(i.description)}</p><div class="card-bottom"><span>${i.recipe?.length?'Recept beschikbaar':'Iteminformatie'}</span><span>↗</span></div></div></button></article>`).join('')||'<div class="empty">Geen items gevonden. Pas je zoekopdracht of filters aan.</div>';}
function toggleStar(id){favs.has(id)?favs.delete(id):favs.add(id);save('oh-favorites',[...favs]);render();if($('detail').open)showDetail(id);}
function showDetail(id){const i=items.find(x=>x.id===id);if(!i)return;const used=items.filter(x=>x.recipe?.some(r=>r.id===id));$('detailContent').innerHTML=`${art(i)}<span class="category">${esc(i.category)}</span><h2>${esc(i.name)}</h2><p>${esc(i.nl)} · ${esc(i.description)}</p><button id="detailStar" class="primary">${favs.has(id)?'★ Opgeslagen':'☆ Bewaar als favoriet'}</button><h3>Hoe krijg je dit?</h3><p>${esc(i.obtain)}</p><div class="facts"><div class="fact"><small>Werkstation</small>${esc(i.station||'Niet ingevuld')}</div><div class="fact"><small>Broncontrole</small>${esc(i.checked||'Nog niet gecontroleerd')}</div></div>${i.recipe?.length?'<h3>Benodigdheden · één receptvariant</h3>'+i.recipe.map(r=>{const ingredient=items.find(x=>x.id===r.id);return `<button class="recipe-row" data-link="${esc(r.id)}" ${ingredient?'':'disabled'}><span>${esc(ingredient?.name||r.id)} ${ingredient?'↗':'(nog niet in catalogus)'}</span><strong>× ${r.amount}</strong></button>`}).join(''):'<p class="warning">Geen recept ingevuld. Dit betekent niet automatisch dat er geen recept bestaat.</p>'}${i.note?'<p class="warning">'+esc(i.note)+'</p>':''}<h3>Gebruikt in deze catalogus</h3>${used.length?used.map(x=>`<button class="recipe-row" data-link="${esc(x.id)}">${esc(x.name)} ↗</button>`).join(''):'<p>Nog geen gekoppelde toepassingen ingevuld.</p>'}<p class="warning">${esc(i.status||'In-game controle open')}<br>Volledige stats, locaties en alle scenario’s zijn nog niet opgenomen.</p><a href="${esc(safeUrl(i.source))}" target="_blank" rel="noopener">Bekijk de bron ↗</a>`;$('detailStar').onclick=()=>toggleStar(id);if(!$('detail').open)$('detail').showModal();history.replaceState(null,'','#item='+encodeURIComponent(id));}
$('grid').onclick=e=>{const star=e.target.closest('[data-star]'),card=e.target.closest('[data-item]');if(star)toggleStar(star.dataset.star);else if(card)showDetail(card.dataset.item)};$('detailContent').onclick=e=>{const b=e.target.closest('[data-link]');if(b)showDetail(b.dataset.link)};$('filters').onclick=e=>{const b=e.target.closest('[data-cat]');if(b){category=b.dataset.cat;render()}};$('search').oninput=render;$('sort').onchange=render;$('all').onclick=()=>{onlyFav=false;render()};$('favorites').onclick=()=>{onlyFav=true;render()};$('manage').onclick=()=>$('admin').showModal();$('setup').onclick=()=>$('help').showModal();document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close').onclick=()=>d.close();d.onclick=e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}});$('detail').addEventListener('close',()=>history.replaceState(null,'',location.pathname+location.search));document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)&&!document.querySelector('dialog[open]')){e.preventDefault();$('search').focus()}});
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(items,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='items.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('import').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>15000000)throw Error('Bestand te groot (maximaal 15 MB).');const data=validate(JSON.parse(await file.text()));if(!save('oh-items',data))throw Error('De browser kan deze gegevens niet bewaren.');items=data;render();$('adminStatus').textContent=data.length+' items geïmporteerd in deze browser.'}catch(err){$('adminStatus').textContent='Import mislukt: '+err.message}finally{e.target.value=''}};
$('addForm').onsubmit=e=>{e.preventDefault();try{const v=Object.fromEntries(new FormData(e.target));const id=v.name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'item';const next={...v,id,recipe:[],checked:'',status:'Handmatig toegevoegd · nog te controleren'};const data=validate([...items,next]);if(!save('oh-items',data))throw Error('Opslaan in deze browser lukt niet.');items=data;render();e.target.reset();$('adminStatus').textContent=v.name+' toegevoegd. Exporteer om te publiceren.'}catch(err){$('adminStatus').textContent=err.message}};
$('reset').onclick=()=>{items=structuredClone(original);save('oh-items',items);render();$('adminStatus').textContent='De oorspronkelijke catalogus is hersteld.'};
(async()=>{try{const response=await fetch('items.json');if(!response.ok)throw Error('Itembestand niet bereikbaar');original=validate(await response.json());const local=read('oh-items');try{items=local?validate(local):structuredClone(original)}catch{items=structuredClone(original)}render();if(location.hash.startsWith('#item=')){try{showDetail(decodeURIComponent(location.hash.slice(6)))}catch{}}}catch(err){$('error').hidden=false;$('error').textContent='De catalogus kon niet laden. Open de website via hosting of een lokale webserver en controleer items.json.';console.error(err)}})();
